// src/views/Settings.vue
<template>
  <AppLayout>
    <section class="page-header">
      <h2>设置</h2>
    </section>
    <el-form label-position="top" :model="draft" class="settings-form">
      <el-form-item label="服务商">
        <el-select v-model="draft.model.provider">
          <el-option label="MiniMax" value="MiniMax" />
          <el-option label="GPT/OpenAI" value="GPT/OpenAI" />
          <el-option label="Claude/Anthropic" value="Claude/Anthropic" />
          <el-option label="DeepSeek" value="DeepSeek" />
          <el-option label="MiMo/Xiaomi" value="MiMo/Xiaomi" />
          <el-option label="自定义" value="自定义" />
        </el-select>
      </el-form-item>
      <el-form-item label="API Key">
        <el-input v-model="draft.model.apiKey" type="password" show-password />
      </el-form-item>
      <el-form-item label="Base URL">
        <el-input v-model="draft.model.baseUrl" />
      </el-form-item>
      <el-form-item label="模型名称">
        <el-input v-model="draft.model.modelName" />
      </el-form-item>
      <el-form-item label="研究背景">
        <el-input v-model="draft.research.background" type="textarea" :rows="5" />
      </el-form-item>
      <el-form-item label="写作风格">
        <el-input v-model="draft.research.writingStyle" type="textarea" :rows="3" />
      </el-form-item>
      <el-button type="primary" :loading="config.saving" @click="save">保存设置</el-button>
    </el-form>
  </AppLayout>
</template>

<script setup lang="ts">
import { onMounted, reactive } from 'vue'
import AppLayout from '@/components/AppLayout.vue'
import { DEFAULT_CONFIG } from '@/lib/core/config'
import type { AppConfig } from '@/lib/llm/types'
import { useConfigStore } from '@/stores/config'

const config = useConfigStore()
const draft = reactive<AppConfig>(structuredClone(DEFAULT_CONFIG))

onMounted(async () => {
  await config.load()
  Object.assign(draft, structuredClone(config.config))
})

async function save() {
  await config.save(structuredClone(draft))
}
</script>

<style scoped>
.settings-form {
  max-width: 760px;
}
</style>

// src/pages/Settings.tsx
import { useEffect, useState } from 'react'
import { Card, Input, Button, Typography, Space, message, Divider } from 'antd'
import { useConfigStore } from '../stores/config'
import type { AppConfig } from '../lib/llm/types'

export default function Settings() {
  const { config, loadConfig, saveConfig } = useConfigStore()
  const [form, setForm] = useState({
    provider: 'openai-compatible' as string,
    baseUrl: '',
    apiKey: '',
    model: '',
    embeddingModel: '',
    researchBackground: '',
  })

  useEffect(() => { loadConfig() }, [loadConfig])

  useEffect(() => {
    if (config) {
      setForm({
        provider: config.provider,
        baseUrl: config.baseUrl,
        apiKey: config.apiKey,
        model: config.model,
        embeddingModel: config.embeddingModel || '',
        researchBackground: '',
      })
    }
  }, [config])

  const handleSave = async () => {
    await saveConfig(form as AppConfig)
    message.success('设置已保存')
  }

  return (
    <div>
      <Typography.Title level={4}>设置</Typography.Title>
      <Card>
        <Typography.Title level={5}>LLM 配置</Typography.Title>
        <Space direction="vertical" style={{ width: '100%' }}>
          <Input placeholder="API Base URL" value={form.baseUrl} onChange={e => setForm(f => ({ ...f, baseUrl: e.target.value }))} />
          <Input.Password placeholder="API Key" value={form.apiKey} onChange={e => setForm(f => ({ ...f, apiKey: e.target.value }))} />
          <Input placeholder="Model" value={form.model} onChange={e => setForm(f => ({ ...f, model: e.target.value }))} />
          <Input placeholder="Embedding Model" value={form.embeddingModel} onChange={e => setForm(f => ({ ...f, embeddingModel: e.target.value }))} />
        </Space>
        <Divider />
        <Typography.Title level={5}>研究背景</Typography.Title>
        <Input.TextArea rows={4} placeholder="描述你的研究方向和兴趣..." value={form.researchBackground} onChange={e => setForm(f => ({ ...f, researchBackground: e.target.value }))} />
        <Divider />
        <Button type="primary" onClick={handleSave}>保存设置</Button>
      </Card>
    </div>
  )
}
